### ISSUE TITLE
Cut/Assemble > Record Search

### ISSUE THREAD

**Issue by NickelAndSuede** [browerjosiahdev/Nickel-Suede#8]
Can we insert the ability on the main screen of the Cut and Assemble modules to scan a kanban and pull up the record.  This would make it much easier to find a kanban  rather than having to search through the entire list (which will be very large--100s)

**Comment by browerjosiahdev** [comment]
@NickelAndSuede this functionality exists if you click the "Add" button in the upper right while on the "Assemble" tab. If you enter the ID of a kanban item (by scanning barcode or typing in) that is cut but not assembled the information will load automatically so you don't have to search through the list.
