### ISSUE TITLE
Assemble > Completion of Kanban

### ISSUE THREAD

**Issue by NickelAndSuede** [browerjosiahdev/Nickel-Suede#9]
When an assembler completes the record for the Kanban under the "Assemble" section, the record should no longer be visible for someone to edit/change--it should "fall off" in a sense.

**Comment by browerjosiahdev** [comment]
@NickelAndSuede as of right now the items that appear on the Cut screen represent items that have already been cut, and items on the Assemble screen have already been assembled. Are you wanting the items that have been cut, but are pending being assembled to appear on the Assemble screen, and then the assembled items to not appear anywhere in the app? If so, is there something you would like to have appear on the Cut screen?

**Comment by NickelAndSuede** [comment]
Ah, I see what you're saying.  I just got done talking with some of the production people, and I'm not sure how we should have this work.  I probably need to discuss with you when you have some availability
